from __future__ import annotations

from copy import deepcopy
from typing import Any


ROUTES: list[dict[str, Any]] = [
    {
        "method": "GET",
        "path": "/",
        "scope": "public",
        "category": "console",
        "summary": "Serve the browser console.",
        "cli": None,
    },
    {
        "method": "GET",
        "path": "/console",
        "scope": "public",
        "category": "console",
        "summary": "Serve the browser console alias.",
        "cli": None,
    },
    {
        "method": "GET",
        "path": "/favicon.ico",
        "scope": "public",
        "category": "console",
        "summary": "Serve the tab icon.",
        "cli": None,
    },
    {
        "method": "GET",
        "path": "/assets/{path}",
        "scope": "public",
        "category": "console",
        "summary": "Serve static browser assets.",
        "cli": None,
    },
    {
        "method": "GET",
        "path": "/health",
        "scope": "public",
        "category": "runtime",
        "summary": "Return platform health, counters, auth state, and LLM readiness.",
        "cli": "--health",
    },
    {
        "method": "GET",
        "path": "/api/contract",
        "scope": "read",
        "category": "runtime",
        "summary": "Return the machine-readable REST API contract.",
        "cli": "--api-contract",
    },
    {
        "method": "GET",
        "path": "/files/{path}",
        "scope": "read",
        "category": "files",
        "summary": "Download generated output files through the REST service.",
        "cli": None,
    },
    {
        "method": "GET",
        "path": "/index",
        "scope": "read",
        "category": "index",
        "summary": "Return the persisted document and comment index.",
        "cli": "--dump-index",
    },
    {
        "method": "GET",
        "path": "/sources",
        "scope": "read",
        "category": "sources",
        "summary": "List source registry records, optionally including missing files.",
        "query": {"include_missing": "optional bool"},
        "cli": "--list-sources [--include-missing-sources]",
    },
    {
        "method": "GET",
        "path": "/sources/detail",
        "scope": "read",
        "category": "sources",
        "summary": "Return source metadata, redacted preview, versions, reviews, risks, and wiki sections.",
        "query": {"path": "required source path", "preview_chars": "optional int"},
        "cli": "--source-detail PATH",
    },
    {
        "method": "GET",
        "path": "/sources/history",
        "scope": "read",
        "category": "sources",
        "summary": "List source version metadata snapshots.",
        "query": {"path": "optional source path", "limit": "optional int"},
        "cli": "--list-source-versions [--source-history PATH] [--source-history-limit N]",
    },
    {
        "method": "GET",
        "path": "/sources/risk",
        "scope": "read",
        "category": "sources",
        "summary": "Return source risk scan summary and details.",
        "cli": "--source-risk-report",
    },
    {
        "method": "GET",
        "path": "/sources/reviews",
        "scope": "read",
        "category": "sources",
        "summary": "List source review and quarantine events.",
        "query": {"path": "optional source path", "limit": "optional int"},
        "cli": "--list-source-reviews [--source-review-path PATH]",
    },
    {
        "method": "GET",
        "path": "/audit",
        "scope": "read",
        "category": "audit",
        "summary": "Return recent audit events.",
        "query": {"limit": "optional int"},
        "cli": "--audit-log [--audit-limit N]",
    },
    {
        "method": "GET",
        "path": "/wiki/lint",
        "scope": "read",
        "category": "wiki",
        "summary": "Validate compiled wiki files and section metadata.",
        "cli": "--lint-wiki",
    },
    {
        "method": "GET",
        "path": "/wiki/sections",
        "scope": "read",
        "category": "wiki",
        "summary": "List compiled wiki section records.",
        "query": {"source_path": "optional source path", "limit": "optional int"},
        "cli": "--list-wiki-sections [--wiki-section-source PATH] [--wiki-section-limit N]",
    },
    {
        "method": "GET",
        "path": "/wiki/pages",
        "scope": "read",
        "category": "wiki",
        "summary": "List compiled wiki pages for same-page browsing.",
        "query": {"limit": "optional int"},
        "cli": None,
    },
    {
        "method": "GET",
        "path": "/wiki/page",
        "scope": "read",
        "category": "wiki",
        "summary": "Return one compiled wiki page by relative path.",
        "query": {"path": "required wiki page path"},
        "cli": None,
    },
    {
        "method": "GET",
        "path": "/wiki/search",
        "scope": "read",
        "category": "wiki",
        "summary": "Search the compiled wiki section index without vector/RAG storage.",
        "query": {"q": "required query", "limit": "optional int"},
        "cli": "--search-wiki QUERY [--wiki-section-limit N]",
    },
    {
        "method": "GET",
        "path": "/reports/governance",
        "scope": "read",
        "category": "reports",
        "summary": "Return the governance report.",
        "cli": "--governance-report",
    },
    {
        "method": "GET",
        "path": "/reports/readiness",
        "scope": "read",
        "category": "reports",
        "summary": "Return enterprise readiness gates.",
        "query": {"groups": "optional repeated group"},
        "cli": "--readiness-report [--group GROUP]",
    },
    {
        "method": "GET",
        "path": "/llm/config",
        "scope": "admin",
        "category": "llm",
        "summary": "Return sanitized LLM and agent configuration.",
        "cli": None,
    },
    {
        "method": "POST",
        "path": "/ask",
        "scope": "read",
        "category": "qa",
        "summary": "Answer one question through the compiled wiki knowledge layer.",
        "body": {"id": "optional question id", "title": "required question", "level": "optional level"},
        "cli": "--ask QUESTION [--id ID] [--level LEVEL]",
    },
    {
        "method": "POST",
        "path": "/explain",
        "scope": "read",
        "category": "qa",
        "summary": "Explain retrieval, safety, and evidence routing for one question.",
        "body": {"id": "optional question id", "title": "required question", "level": "optional level"},
        "cli": "--explain-ask QUESTION [--id ID] [--level LEVEL]",
    },
    {
        "method": "POST",
        "path": "/reindex",
        "scope": "admin",
        "category": "index",
        "summary": "Rebuild and persist the file/comment/source index.",
        "cli": "--reindex",
    },
    {
        "method": "POST",
        "path": "/sources/import",
        "scope": "admin",
        "category": "sources",
        "summary": "Import a local file or public URL into docs and rebuild source metadata.",
        "body": {"source": "required path or URL", "title": "optional title", "category": "optional category"},
        "cli": "--import-source PATH_OR_URL [--import-title TITLE] [--import-category CATEGORY]",
    },
    {
        "method": "POST",
        "path": "/sources/status",
        "scope": "admin",
        "category": "sources",
        "summary": "Set source status to active or quarantined and record a review event.",
        "body": {"path": "required source path", "status": "required active|quarantined", "reason": "optional", "actor": "optional"},
        "cli": "--set-source-status PATH --source-status active|quarantined",
    },
    {
        "method": "POST",
        "path": "/wiki/compile",
        "scope": "admin",
        "category": "wiki",
        "summary": "Compile docs into the maintained Markdown wiki layer.",
        "cli": "--compile-wiki",
    },
    {
        "method": "POST",
        "path": "/groups/run",
        "scope": "admin",
        "category": "qa",
        "summary": "Run one or more question groups and write answer files.",
        "body": {"groups": "optional group or group list"},
        "cli": "--group GROUP",
    },
    {
        "method": "POST",
        "path": "/slides/generate",
        "scope": "admin",
        "category": "workbench",
        "summary": "Generate a presentation brief file from a topic.",
        "body": {"topic": "required topic", "slide_count": "optional int"},
        "cli": "--generate-brief TOPIC [--slide-count N]",
    },
    {
        "method": "POST",
        "path": "/reports/governance/export",
        "scope": "admin",
        "category": "reports",
        "summary": "Write the governance report to output/reports.",
        "cli": "--export-governance-report",
    },
    {
        "method": "POST",
        "path": "/reports/evaluation",
        "scope": "admin",
        "category": "reports",
        "summary": "Evaluate question groups and return quality metrics.",
        "body": {"groups": "optional group or group list"},
        "cli": "--evaluation-report [--group GROUP]",
    },
    {
        "method": "POST",
        "path": "/reports/evaluation/export",
        "scope": "admin",
        "category": "reports",
        "summary": "Write question evaluation reports to output/reports.",
        "body": {"groups": "optional group or group list"},
        "cli": "--export-evaluation-report [--group GROUP]",
    },
    {
        "method": "POST",
        "path": "/reports/readiness",
        "scope": "admin",
        "category": "reports",
        "summary": "Return enterprise readiness gates using explicit POST group selection.",
        "body": {"groups": "optional group or group list"},
        "cli": None,
    },
    {
        "method": "POST",
        "path": "/reports/readiness/export",
        "scope": "admin",
        "category": "reports",
        "summary": "Write enterprise readiness report files.",
        "body": {"groups": "optional group or group list"},
        "cli": "--export-readiness-report [--group GROUP]",
    },
    {
        "method": "POST",
        "path": "/reports/release/export",
        "scope": "admin",
        "category": "reports",
        "summary": "Write a metadata-only release bundle.",
        "body": {"groups": "optional group or group list", "include_evaluation": "optional bool"},
        "cli": "--export-release-bundle [--group GROUP] [--release-include-evaluation]",
    },
    {
        "method": "POST",
        "path": "/llm/config",
        "scope": "admin",
        "category": "llm",
        "summary": "Update LLM and named agent configuration.",
        "cli": None,
    },
    {
        "method": "POST",
        "path": "/llm/test",
        "scope": "admin",
        "category": "llm",
        "summary": "Validate one named LLM agent and optionally run a live probe.",
        "body": {"agent_name": "required agent name", "live": "optional bool"},
        "cli": "--test-llm-agent AGENT [--test-llm-live]",
    },
]


def api_contract() -> dict[str, Any]:
    return {
        "status": "ok",
        "schema_version": 1,
        "name": "Stonehenge Wiki REST API",
        "project": "stonehenge-wiki",
        "auth": {
            "header": "X-STONEHENGE-WIKI-TOKEN",
            "scopes": {
                "public": "No token required.",
                "read": "Requires read or admin token when API auth is enabled.",
                "admin": "Requires admin token when API auth is enabled.",
            },
        },
        "architecture": {
            "knowledge_mode": "compiled_wiki",
            "rag": False,
            "cli_boundary": "Rust CLI calls REST API only; it does not call Python or opencode directly.",
        },
        "route_count": len(ROUTES),
        "routes": deepcopy(ROUTES),
    }
